# Generated by Django 5.0.6 on 2024-10-10 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quality',
            field=models.DecimalField(decimal_places=1, default=5.0, max_digits=3),
        ),
    ]
